#!/bin/bash

########################################
# man git-config | grep "core.gitproxy"  # 查看一些代理的用法
# The result in ~/.gitconfig
# And you can just copy below into ~/.gitconfig
# 中文乱码
# 图形化Diff/Merge
# 还原英文界面，更好懂
# 最有价值的，就是Git的Diff/Merge外部工具TortoiseMerge配置
# Linux 用户可以忽略

# 配置Git的时候，加上--global是针对当前用户起作用的，如果不加，那只针对当前的仓库起作用。
# 每个仓库的Git配置文件都放在.git/config文件中
# 当前用户的Git配置文件放在用户主目录下的一个隐藏文件.gitconfig中
########################################
# 查看
# git config --global -l # 产看git config --global 的所有设置

# 全局提交用户名与邮箱
git config --global user.name "coderdr31"
git config --global user.email 1683751393@qq.com

# 解决 git status 显示中文为ASCII
git config --global core.quotepath false

# alias
git config --global alias.br 'branch -a'
git config --global alias.clog 'clog = log --date=short --pretty=format:"%Cred%ad %Cblue%h %Cgreen%an %Creset%s%C(yellow)%d"'
git config --global alias.slog 'log --date=short --pretty=format:"%C(124)%ad %C(24)%h %C(34)%an %C(252)%s%C(178)%d"'
git config --global alias.llog 'log --date=short --format="%C(94)--------------------------------------------------------------------------------%n%C(24)%h %C(124)%ad %C(34)%an %C(22)<%ae>%C(130)%d%n%C(178) %s%n%n%B(1)"'
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# 配色
git config --global color.branch auto
git config --global color.branch.current green
git config --global color.branch.local yellow
git config --global color.branch.remote red

git config --global color.diff auto
git config --global color.diff.mete yellow

git config --global color.grep auto
git config --global color.grep.match green

git config --global color.interactive auto
git config --global color.showbranch auto

git config --global color.status auto
git config --global color.status.changed yellow

git config --global color.ui auto

# 这是个很有效的配置，修改后速度有质的提升
git config --global http.postBuffer 524288000

# 中文编码支持
#echo "export LESSCHARSET=utf-8" > $HOME/.profile
#git config --global gui.encoding utf-8
#git config --global i18n.commitencoding utf-8
#git config --global i18n.logoutputencoding gbk

# 全局编辑器，提交时将COMMIT_EDITMSG编码转换成UTF-8可避免乱码
#git config --global core.editor vim

# 差异工具配置
#git config --global diff.external git-diff-wrapper.sh
#git config --global diff.tool tortoise
#git config --global difftool.tortoise.cmd 'TortoiseMerge -base:"$LOCAL" -theirs:"$REMOTE"'
#git config --global difftool.prompt false

# 合并工具配置
#git config --global merge.tool tortoise
#git config --global mergetool.tortoise.cmd 'TortoiseMerge -base:"$BASE" -theirs:"$REMOTE" -mine:"$LOCAL" -merged:"$MERGED"'
#git config --global mergetool.prompt false

# 别名设置
#git config --global alias.dt difftool
#git config --global alias.mt mergetool

# 取消 $ git gui 的中文界面，改用英文界面更易懂
#if [ -f "/share/git-gui/lib/msgs/zh_cn.msg" ]; then
    #rm /share/git-gui/lib/msgs/zh_cn.msg
#fi

